### PR TITLE
Improving performance of lead svg animation

### PR DESCRIPTION
**Pull request by orlando**
# Context
This PR improves the performance of the svg animation in retina devices, by promoting the lead-svg to its own layer and that way preventing layout thrashing.

Also, we are adjusting times for intercom and svg animation duration

## Links
* https://aerotwist.com/blog/on-translate3d-and-layer-creation-hacks/

## Media

image

**Before:** https://dl.dropbox.com/s/h4gvqsgnn96w1ym/screencast_2017-04-26_13-26-39.mp4?dl=0
**After:** https://dl.dropbox.com/s/gwzs8tc8e0s4ru5/screencast_2017-04-26_13-21-56.mp4?dl=0

### CODE REVIEW

**Review by TheMightyPenguin — COMMENTED** [review]
Looks good, but you need to run `gulp css` to update the `css/main.min.css` file!

**Comment by orlando** [comment]
Oh yeah, I left these files out of this PR so you don't have conflicts in the next PR

**Comment by orlando** [comment]
@victor ^

**Comment by orlando** [comment]
ok I'll add these files too, hope isn't a problem later on

**Review by duranmla — APPROVED** [review]
LGTM

**Pull request merged**
